### ISSUE TITLE
Feature Request: Color for nodes, styling text

### ISSUE THREAD

**Issue by tobiasweise** [stweise/rico-cluster-qt#1]
Hi! What a great project. Thanks! For future versions, it would be great to have the possibility to change the color of nodes and to style the node text (**bold**, *italics*, color). Let me know if I can help.

**Comment by stweise** [comment]
Hi,
thanks so much for raising the first issue.

The main purpose of this tool is to be able to quickly "brain dump" your thoughts into a rico cluster. I personally find the possibility to stylize the node labels or the nodes to be a distraction from that. Just like spell checking red lines in any form of text entry.

I will try to think of a way of doing this as an option. The tool does not have an options/preferences menu and window yet. I will thus delay implementing this unless I have it.

Please note, that I am tracking future features in a markdown file (see NEXT_FEATURES.md)
I added your requested features there.
